Document required Python version
The error I was getting is

> AttributeError: module 'collections' has no attribute 'MutableSet'

Googled the error, sounded like it might be related to [1]. Downgrading
Python to version used here worked.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1791952